# Generated by Django 4.1.4 on 2022-12-10 17:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='thumb_img')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.CharField(max_length=30)),
            ],
        ),
    ]
