# Generated by Django 4.1.4 on 2022-12-11 02:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_blog_mini_descricao_alter_blog_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('esportes', 'Esportes'), ('noticias', 'Notícias'), ('cinema', 'Cinema'), ('tecnologia', 'Tecnologia'), ('finanças', 'Finanças')], default=False, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='descricao',
            field=ckeditor.fields.RichTextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='mini_descricao',
            field=models.CharField(max_length=2000),
        ),
    ]
