# Generated by Django 4.1.4 on 2022-12-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blog_categoria_alter_blog_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='categoria',
            field=models.CharField(choices=[('esportes', 'Esportes'), ('cinema', 'Cinema'), ('tecnologia', 'Tecnologia'), ('finanças', 'Finanças')], max_length=30),
        ),
    ]
